name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Mocha
        run: npm install --save-dev mocha

      - name: Change permissions (optional)
        run: chmod +x ./node_modules/.bin/mocha

      - name: Run tests
        run: npm test
